language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -e .[test,ci]
script:
- pytest --cov=gces --cov-report annotate
deploy:
  provider: pypi
  user: debonzi
  password:
    secure: GgfXyKBzAfOs8pYK5NV+E/dF7mmnKLsNLKahSuP6k4N19UwYWlFiWQlCDVh883Wf1qgayJOb4gtLXr9s0vxws++Sagq6V9mOTVIs+WmwAdL0j3Di55Pyicl2VXsZbx/z6YEzE+2sbSq6kTMX65qwqA+ywqAA2rPbl2ABzY0Z938JGiwviq7ALUhbJiR+lUEUQIbzUjsKpmMIe6BWvd46an5UXUaHT4BP8OqlXZrYCqt/3Ef/xBNVibz/galg1xa1blwi+vJuq9y8XYv247hFA4tkOn6VtcpMMRenSJw8M7ob+80nJ11W8DDQfrTYxIaHag/SgzxHN7Weg4UzKa+U0dF3ydDCeUbb+2l51FPafqcUxfwGcHY5ZqyDR6P7QymfIS4asW8ZXe5NFx5FT9IY7l1XQlCPuEVPHkFxRC1pLiARjg8C7XI5m/1LY8yq5TVFkc7CLnJG+RtGyAqXAMOdePPsqTL0PP8fYyO1CjrmCmuTRq9ioT30sBiFXHHaqK8081pOFl4LtrvWmyUDeGZMDvT4cQW5RdTliVSqQdHj7LrHcn2AX8ZUSTgG0F1TeLy+4Pr2UZqFgQKx06UK4UDucvW3b4j/3askt6wbk6/ypXaTMNjwwO2sKhdqGdXuDUr3aBMTkKcAvo6ngMZZv/NjjbaV5Iq7qaZVMSVoJXBiyPM=
  on:
    tags: true
    branch: master
    python: '3.6'
after_success:
- coveralls
